### ISSUE TITLE
Adding a child to PBXVariantGroup

### ISSUE THREAD

**Issue by nunogoncalves** [mjmsmith/pbxplorer#1]
Hi,

So I'm trying to add a file reference that is a translation file. So I have: 

```
/* Begin PBXVariantGroup section */
        85912AC51BE0CD1C0016107B /* Main.storyboard */ = {
            isa = PBXVariantGroup;
            children = (
                85912AC61BE0CD1C0016107B /* Base */,
            );
            name = Main.storyboard;
            sourceTree = "<group>";
        };      
/* End PBXVariantGroup section */
```

And I want to add: 

```
    123456789ABCDEF012345678 /* en */,
```

Having as a result: 

```
/* Begin PBXVariantGroup section */
        85912AC51BE0CD1C0016107B /* Main.storyboard */ = {
            isa = PBXVariantGroup;
            children = (
                85912AC61BE0CD1C0016107B /* Base */,
                123456789ABCDEF012345678 /* en */,
            );
            name = Main.storyboard;
            sourceTree = "<group>";
        };      
/* End PBXVariantGroup section */
```

For what I understand reading the code, this isn't supported, right? 

Thank you

**Comment by nunogoncalves** [comment]
I'll probably make my own parser, using plutil and adding my own entries as they are quite specific.

**Comment by mjmsmith** [comment]
Hi, you’re correct, variants aren’t supported.

**Comment by mjmsmith** [comment]
PBXVariantGroup added as a subclass of PBXGroup in v1.1.0.

PBXGroup#subgroups returns all of the subgroups, including PBXVariantGroup.
PBXGroup#variant_groups returns only the PBXVariantGroup subgroups.
